# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_books_users_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
