# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_books_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='books',
            name='ISBN',
            field=models.IntegerField(error_messages={}),
        ),
        migrations.AddField(
            model_name='challenges',
            name='challengebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.Books'),
        ),
    ]
