# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_auto_20160722_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chalname', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='challenges',
            name='challengebook',
        ),
        migrations.DeleteModel(
            name='Challenges',
        ),
        migrations.AddField(
            model_name='books',
            name='challengebooklist',
            field=models.ManyToManyField(to='Books.Challenge'),
        ),
    ]
