# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_auto_20160722_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=200)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.Challenge')),
            ],
        ),
    ]
