# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_challengeitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeitem',
            name='list',
        ),
        migrations.DeleteModel(
            name='ChallengeItem',
        ),
    ]
