# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 16:12
from __future__ import unicode_literals

from django.db import migrations
import djorm_pgarray.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0007_auto_20160722_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='book_in_challenge',
            field=djorm_pgarray.fields.ArrayField(blank=True, default=None, null=True),
        ),
    ]
