# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 08:37
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0010_auto_20160729_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='authors/title'),
        ),
    ]
