# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0012_auto_20160802_0504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='photo',
            new_name='coverpic',
        ),
    ]
