# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0013_auto_20160802_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='coverpic',
            field=models.ImageField(blank=True, null=True, upload_to='coverpic_path'),
        ),
    ]
